config/routes.rb
Rails.application.routes.draw do
  resources :users_plofile
  # 借りる機能に関するルーティング
  get 'confirm/:id', to: 'rentals#confirm', as: 'rental'
  post 'rental/:id', to: 'rentals#create', as: 'create_rental'
  resources :rentals 
  # post 'rentals/confirm', to:'rentals#confirm'
  
  # ログイン関連のルーティング
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # usersに関するルーティング
  resources :users

  # トップページを表示するルーティング
  root 'rooms#index'
  # roomsに関するルーティング
  
  get 'rooms/index'
  get 'rooms/search'
  get 'rooms/:id', to: 'rooms#show', as: 'room'
  get 'rooms/new'
  get 'rooms/edit'

  # hostsに関するルーティングを一括指定
  resources :hosts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'tops/search', to: 'tops#search'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/host.rb
class Host < ApplicationRecord
	# モデルと紐づける設定
	has_one_attached :image

	# userモデルと結びつける
	belongs_to :user
end

app/models/rental.rb
class Rental < ApplicationRecord

  # userモデルと結びつける
  belongs_to :user
  
  # 開始日を検証
  validates :rent_start_day, presence: true #開始日がnillの場合はこっちの検証

  validate :start_check #開始日が今日より前の場合
  def start_check
    errors.add(:rent_start_day, "は今日より前の日付を登録することはできません。") if rent_start_day&. < Date.today
  end

  # 終了日を検証
  validates :rent_end_day, presence: true #終了日がnillの場合はこっちの検証

  validate :end_check #終了日が開始日より前の場合
  def end_check
    errors.add(:rent_end_day, "は開始日より前の日付を入力することは出来ません。") if rent_end_day&. < rent_start_day
  end

  # 人数を検証  
  validates :people, inclusion: {in: 1..10}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  # hostモデルと結びつける
  has_many :hosts
  
  # rentalモデルと結びつける
  has_many :rentals
  
  validates :name, presence:true
  validates :email,presence:true,uniqueness: true
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  has_one_attached :icon
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ヘルパーメソッドをすべてのページから使えるようにする
  include SessionsHelper
  # ヘルパーメソッド指定をすることですべてのビューから使用できるようにする。
  helper_method :current_user

  private

  # ログイン済みユーザーかどうか確認
  def logged_in_user
    unless logged_in?
      redirect_to login_url
    end
  end

  def current_user
  # ||=は左辺がnilでなければ右辺を代入するという意味
  # if session[:user_id]
  # @current_user ||= User.find_by(id: session[:user_id])
  # end と同じ
  # ログインしていた場合、Userモデルから
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  # binding.pry
  end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  # logged_in_userをindexとnewとcreateの前に作動させることによりログインしているかチェックしている
  before_action :logged_in_user, only:[:index,:new, :create]

  def index
    @hosts = current_user.hosts
  end

  def show
  end

  def new
    @host = Host.new
  end

  def create
    @host = current_user.hosts.new(host_params)
    if @host.save
      redirect_to hosts_path, notice: "ホストとして物件を登録することができました。"
    else
      render :new
    end
  end

  def edit
  end

  private
  def host_params
    params.require(:host).permit(:room_name,:room_introduction,:room_charge,:room_address,:image)
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController

  before_action :logged_in_user, only:[:index, :new, :confirm, :create]

  def index
    @rental = current_user.rentals
    binding.pry
  end

  def new
    @rentals = Rental.new
    binding.pry
  end

  def confirm
    @rentals = current_user.rentals.new(rental_params)
    @room = Host.find(params[:id])
    binding.pry
    # valid?はエラーがあればfalseを返す
    unless @rentals.valid?
      # 入力前の画面に戻す
      render "rooms/show"
    end
  end

  def create
    @rentals = current_user.rentals.new(rental_params)
    # renderで遷移するrooms/showに渡すインスタンス変数を定義する
    @room = Host.find(params[:id])
    binding.pry

    # 戻るボタンが押された時の処理
    if params[:back].present?
      render "rooms/show"
      return
    end

    if @rentals.save
      binding.pry
      redirect_to rentals_path, notice: "予約が完了しました。"
    else
      binding.pry
      render "rooms/show"
    end
  end

  def show
  end

  def edit
  end

  private
  def rental_params
    params.require(:rental).permit(:id,:rent_room_name, :rent_room_intro,:rent_start_day, :rent_end_day, :rent_room_charge, :people)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
# 各アクションが動作する前に
  before_action :search

  def index
    
  end

  def search
    @q = Host.ransack(params[:q])
    @rooms = @q.result(distinct: true)
    # binding.pry
  end

  def show
    # binding.pry
    @room = Host.find(params[:id])
    # binding.pry
  end

  def new
  end

  def edit
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # 送られてきたメールアドレスで、Userモデルのemailカラムからユーザーを検索する
    # 該当したユーザーのレコードをuser変数に格納
    user = User.find_by(email: session_params[:email])

    # ユーザーが見つかった場合は、送られてきたパスワードをauthenticateメソッドで認証可能か判断する
    # &.はuser（レシーバ）がnilの場合でもエラーが出ないようにするメソッド
    if user&.authenticate(session_params[:password])
      # 認証に成功した場合ユーザーidをセッションに格納
      session[:user_id] = user.id
      redirect_to root_path, notice: 'ログインしました'
    else
      render :new, notice: 'ログインに失敗しました'
    end
  end

  def destroy
    reset_session
    binding.pry
    redirect_to root_url, notice: 'ログアウトしました',status: :see_other
  end

  private
  # emailカラムとpasswordカラムだけデータベースに保存
    def session_params
      params.require(:session).permit(:email, :password)
    end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def search
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
    # Userクラスをインスタンス化
    @user = User.new
  end

  def create
    # privateメソッドにより安全化されたuserパラメーターをuser_paramsメソッドで取得して、Userオブジェクトを作成する
    @user = User.new(user_params)
    # binding.pry
    # save!メソッドでデータベースに登録
    if @user.save
      # トップ画面に遷移
      redirect_to root_path,notice: "登録に成功しました"
    else
      render :new
    end
  end

  def edit
  end

  private
  # user_paramsメソッドで指定したカラム名以外の登録をできなくする
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/users_profile_controller.rb
class UsersProfileController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/users_profile_helper.rb
module UsersProfileHelper
end

app/views/hosts/edit.html.slim
h1 Hosts#edit
p Find me in app/views/hosts/edit.html.slim

app/views/hosts/index.html.slim
h1 登録した宿泊先一覧
.mb-3 
table.table.table-hover 
	thead.thead-default 
		tr 
			th = "ルーム名"
			th = "ルーム紹介"
			th = "ルーム料金"
			th = "登録日時"
			th = "ルーム写真"
	tbody 
		- @hosts.each do |host|
			tr 
				td = host.room_name 
				td = host.room_introduction 
				td = host.room_charge 
				td = host.created_at.strftime("%Y-%m-%d")
				td = image_tag host.image, class: "host_image" if host.image.attached?

app/views/hosts/new.html.slim
h1 ホストになる

= form_with model: @host, local: true do |f|
  .form-group 
    = f.label :room_name,"ルーム名"
    = f.text_field :room_name, class: 'form-control', id: 'host_room_name'
  .form-group 
    = f.label :room_introduction,"ルーム紹介"
    = f.text_area :room_introduction, rows:5, class: 'form-control', id: 'host_room_introduction'
  .form-group 
    = f.label :image,"ルーム画像"
    = f.file_field :image, class: 'form-control'
  .form-group 
    = f.label :room_charge,"ルーム料金"
    = f.text_field :room_charge, class: 'form-control', id: 'host_room_charge'
  .form-group 
    = f.label :room_address,"住所"
    = f.text_field :room_address, class: 'form-control', id: 'host_room_address'


  = f.submit "登録する", class: 'btn btn-primary'

app/views/hosts/show.html.slim
h1 Hosts#show
p Find me in app/views/hosts/show.html.slim

app/views/rentals/confirm.html.slim
h1 登録内容の確認
.rental_form 
  = form_with model: @rentals, local: true, url: create_rental_path, data: { turbo: false } do |f|
    table.table.table-hover 
      tbohy 
        tr 
          th = "宿泊開始日"
          td = @rentals.rent_start_day.strftime("%Y-%m-%d")
          = f.hidden_field :rent_start_day
        tr 
          th = "宿泊終了日"
          td = @rentals.rent_end_day.strftime("%Y-%m-%d")
          = f.hidden_field :rent_end_day
        tr 
          th = "人数"
          td = @rentals.people
        tr 
          th = "合計金額"
          td = @rentals.rent_room_charge * @rentals.people * (@rentals.rent_end_day.strftime("%d").to_i - @rentals.rent_start_day.strftime("%d").to_i)
        / 隠しフォーム
    = f.hidden_field :people, :value => @rentals.people
    = f.hidden_field :rent_room_charge, :value => @rentals.rent_room_charge * @rentals.people * (@rentals.rent_end_day.strftime("%d").to_i - @rentals.rent_start_day.strftime("%d").to_i)
    = f.hidden_field :rent_room_name, :value => @rentals.rent_room_name
    = f.hidden_field :rent_room_intro, :value => @rentals.rent_room_intro
    = f.submit "戻る", name: 'back', class: 'btn btn-primary'
    = f.submit "予約する", class: 'btn btn-primary'

app/views/rentals/edit.html.slim
h1 Rentals#edit
p Find me in app/views/rentals/edit.html.slim

app/views/rentals/index.html.slim
h1 予約した宿泊先一覧
.mb-3 
table.table.table-hover 
	thead.thead-default 
		tr 
			th = "ルーム名"
			th = "ルーム紹介"
			th = "ルーム料金"
			th = "宿泊開始日"
			th = "宿泊終了日"
	tbody 
		- @rental.each do |rental|
			tr 
				td = rental.rent_room_name 
				td = rental.rent_room_intro
				td = rental.rent_room_charge 
				td = rental.rent_start_day.strftime("%Y-%m-%d")
				td = rental.rent_end_day.strftime("%Y-%m-%d")

app/views/rentals/new.html.slim
h1 Rentals#new
p Find me in app/views/rentals/new.html.slim

app/views/rentals/show.html.slim
h1 Rentals#show
p Find me in app/views/rentals/show.html.slim

app/views/rooms/edit.html.slim
h1 Rooms#edit
p Find me in app/views/rooms/edit.html.slim

app/views/rooms/index.html.slim
.image_container 
	img.image src="/assets/0admkt04.jpg" alt="背景画像１"/
	img.image src="/assets/hokaido-.jpeg" alt="背景画像２"/ 
	img.image src="/assets/東京フリー.jpeg" alt="背景画像３"/ 

/ 検索フォーム
h2 エリアを検索
= search_form_for @q, url: rooms_search_path, class: 'mb-5' do |f|
  .form-group.row  
    / room_addressカラムに対して部分一致検索
    = f.search_field :room_address_cont, class: 'form-control'
  .form-group 
    = f.submit class: 'btn btn-secondary' 

h2 フリーワード検索
= search_form_for @q, url: rooms_search_path, class: 'mb-5' do |f|
  .form-group.row  
    / すべてのカラムに対して部分一致検索
    = f.search_field :room_name_or_room_introduction_or_room_address_or_room_charge_cont, class: 'form-control'
  .form-group 
    = f.submit class: 'btn btn-secondary' 

app/views/rooms/new.html.slim
h1 Rooms#new
p Find me in app/views/rooms/new.html.slim

app/views/rooms/search.html.slim
h1 検索結果
.mb-3 
table.table.table-hover 
  thead.thead-default 
    tr 
      th = "ルーム名"
      th = "ルーム料金"
      th = "ルーム写真"
    tbody 
      - @rooms.each do |room| 
        tr
          td = link_to(room.room_name, room_path(room), class:"search_list")
          td = link_to(room.room_charge, room_path(room), class:"search_list") 
          - if room.image.attached?
            td = image_tag room.image, class: "host_image" 

app/views/rooms/show.html.slim
.conteiner  
  h1 宿泊先予約画面
  = render "shared/error", obj:@rentals
  .row 
    .col-8 
      div 
        -if @room.image.attached?
          = image_tag @room.image, class: 'rental_image'
      .col-sm-8
        .card 
          .card-body 
            h4 = @room.room_name
            p = @room.room_introduction
    .col-4.shadow.p-3.bg-body.rounded.border.mr-5
      .charge_form.m-4 
        h4.text-center = "¥#{@room.room_charge}/日"
      .rental_form 
        = form_with model: Rental.new, local: true, method: :get, url: rental_path, data: { turbo: false } do |f|
          .form-group.mb-5
            = f.label :rent_start_day, "宿泊開始日"
            = f.date_field :rent_start_day, class: 'form-control'
          .form-group.mb-5 
            = f.label :rent_end_day, "宿泊終了日"
            = f.date_field :rent_end_day, class: 'form-control'
          .form-group.mb-5 
            = f.label :people, "人数"
            = f.select :people, [["1",1],["2",2],["3",3],["4",4],["5",5],["6",6],["7",7],["8",8],["9",9],["10",10]],{selected: 1},{class: 'form-control'}
          = f.hidden_field :rent_room_name, :value => @room.room_name
          = f.hidden_field :rent_room_intro, :value => @room.room_introduction
          = f.hidden_field :rent_room_charge, :value => @room.room_charge
          = f.submit "予約内容確認", class: 'btn btn-primary'

app/views/tops/search.html.slim
.image_container 
	img.image src="/assets/0admkt04.jpg" alt="背景画像１"/
	img.image src="/assets/nebuta.jpeg" alt="背景画像２"/ 
	img.image src="/assets/東京フリー.jpeg" alt="背景画像３"/ 
h1 検索ボックス

app/views/users/edit.html.slim
h1 Users#edit
p Find me in app/views/users/edit.html.slim

app/views/users/index.html.slim
h1 Users#index
p Find me in app/views/users/index.html.slim

app/views/users/new.html.slim
h1 ユーザー登録画面

= form_with model: @user, local: true do |f|
  .form-group 
    = f.label :name,"名前"
    = f.text_field :name, class: 'form-control', id: 'user_name'
  .form-group 
    = f.label :email,"メールアドレス"
    = f.text_field :email, class: 'form-control', id: 'user_email'
  .form-group 
    = f.label :password,"パスワード", id: 'user_password'
    = f.password_field :password, class: 'form-control'
  .form-group 
    = f.label :password_confirmation,"パスワード(確認)", id: 'user_password'
    = f.password_field :password_confirmation, class: 'form-control'

  = f.submit "登録する", class: 'btn btn-primary'

app/views/users/show.html.slim
h1 Users#show
p Find me in app/views/users/show.html.slim

app/views/users_profile/edit.html.slim
h1 UsersProfile#edit
p Find me in app/views/users_profile/edit.html.slim

app/views/users_profile/index.html.slim
h1 UsersProfile#index
p Find me in app/views/users_profile/index.html.slim

app/views/users_profile/new.html.slim
h1 UsersProfile#new
p Find me in app/views/users_profile/new.html.slim

app/views/users_profile/show.html.slim
h1 UsersProfile#show
p Find me in app/views/users_profile/show.html.slim